In [1]:
import cv2
import numpy as np

img = cv2.imread('s.jpg')
print(img.shape)

w = img[:, 0:1]
print(w.shape)
for i in range(1, 638):
    wc = img[:, i: i + 1]
    for j in range(0, 479):
        print(w[j][0], wc[j][0])
        if not np.array_equal(w[j][0], wc[j][0]):
            img[j, i] = [0, 255, 0]
    
        
cv2.imshow('image', img)
cv2.waitKey(1)
cv2.destroyAllWindows()


(479, 638, 3)
(479, 1, 3)
[160 194 207] [161 195 208]
[164 198 211] [194 228 241]
[158 192 205] [196 230 243]
[164 198 211] [196 228 241]
[164 196 209] [198 230 243]
[163 195 208] [198 230 243]
[165 197 210] [198 230 243]
[160 192 205] [200 232 245]
[162 194 207] [203 235 248]
[163 195 208] [197 229 242]
[165 197 210] [197 229 242]
[161 193 206] [198 230 243]
[163 195 208] [202 234 247]
[163 195 208] [197 229 242]
[165 197 210] [197 229 242]
[163 195 208] [198 230 243]
[162 194 207] [203 235 248]
[164 196 209] [198 230 243]
[164 196 209] [196 228 241]
[162 194 207] [200 232 245]
[162 194 207] [201 233 246]
[164 196 209] [198 230 243]
[164 196 209] [197 229 242]
[162 194 207] [197 229 242]
[163 195 208] [204 236 249]
[163 195 208] [198 230 243]
[163 195 208] [195 227 240]
[163 195 208] [199 231 244]
[163 195 208] [201 233 246]
[163 195 208] [199 231 244]
[164 196 209] [197 229 242]
[164 196 209] [197 229 242]
[163 194 209] [202 233 248]
[162 193 208] [198 229 244]
[163 194 209] [196 227


[  0 255   0] [204 236 249]
[  0 255   0] [199 231 244]
[  0 255   0] [197 229 242]
[  0 255   0] [201 233 246]
[  0 255   0] [203 235 248]
[  0 255   0] [199 231 244]
[  0 255   0] [197 229 242]
[  0 255   0] [199 231 244]
[  0 255   0] [203 235 248]
[  0 255   0] [201 233 246]
[  0 255   0] [200 232 245]
[  0 255   0] [201 233 246]
[  0 255   0] [201 233 246]
[  0 255   0] [199 231 244]
[  0 255   0] [198 230 243]
[  0 255   0] [199 231 244]
[  0 255   0] [204 233 248]
[  0 255   0] [202 231 246]
[  0 255   0] [199 230 245]
[  0 255   0] [199 230 245]
[  0 255   0] [200 231 246]
[  0 255   0] [201 233 246]
[  0 255   0] [199 231 244]
[  0 255   0] [198 230 243]
[  0 255   0] [204 236 249]
[  0 255   0] [201 233 246]
[  0 255   0] [198 230 243]
[  0 255   0] [199 231 244]
[  0 255   0] [202 234 247]
[  0 255   0] [202 234 247]
[  0 255   0] [199 231 244]
[  0 255   0] [197 229 242]
[  0 255   0] [201 235 248]
[  0 255   0] [200 234 247]
[  0 255   0] [198 230 243]
[  0 255   0] [198 

 [181 218 232]
[  0 255   0] [187 224 238]
[  0 255   0] [188 222 238]
[  0 255   0] [187 224 238]
[  0 255   0] [185 222 236]
[  0 255   0] [186 221 235]
[  0 255   0] [190 223 239]
[  0 255   0] [188 220 239]
[  0 255   0] [182 218 234]
[  0 255   0] [184 223 237]
[  0 255   0] [187 227 239]
[  0 255   0] [185 223 235]
[  0 255   0] [183 220 234]
[  0 255   0] [183 221 239]
[  0 255   0] [188 224 240]
[  0 255   0] [199 229 240]
[  0 255   0] [228 245 248]
[  0 255   0] [164 198 211]
[  0 255   0] [197 229 242]
[  0 255   0] [198 230 243]
[  0 255   0] [199 231 244]
[  0 255   0] [202 234 247]
[  0 255   0] [200 232 245]
[  0 255   0] [198 230 243]
[  0 255   0] [200 232 245]
[  0 255   0] [200 229 243]
[  0 255   0] [201 230 244]
[  0 255   0] [203 232 246]
[  0 255   0] [198 230 243]
[  0 255   0] [200 232 245]
[  0 255   0] [199 231 244]
[  0 255   0] [201 233 246]
[  0 255   0] [199 231 244]
[  0 255   0] [197 229 242]
[  0 255   0] [200 232 245]
[  0 255   0] [201 233 246]
[  0 

 [202 231 245]
[  0 255   0] [203 232 246]
[  0 255   0] [202 231 245]
[  0 255   0] [200 229 243]
[  0 255   0] [203 232 246]
[  0 255   0] [201 230 244]
[  0 255   0] [199 228 242]
[  0 255   0] [200 229 243]
[  0 255   0] [201 233 246]
[  0 255   0] [202 234 247]
[  0 255   0] [200 232 245]
[  0 255   0] [198 230 243]
[  0 255   0] [201 233 246]
[  0 255   0] [197 229 242]
[  0 255   0] [197 229 242]
[  0 255   0] [201 230 244]
[  0 255   0] [202 231 245]
[  0 255   0] [204 233 248]
[  0 255   0] [203 232 247]
[  0 255   0] [198 229 244]
[  0 255   0] [198 231 247]
[  0 255   0] [157 193 209]
[  0 255   0] [182 221 236]
[  0 255   0] [180 219 234]
[  0 255   0] [184 224 242]
[  0 255   0] [180 220 238]
[  0 255   0] [184 224 242]
[  0 255   0] [177 217 235]
[  0 255   0] [179 222 241]
[  0 255   0] [180 223 242]
[  0 255   0] [177 220 239]
[  0 255   0] [177 220 239]
[  0 255   0] [181 224 243]
[  0 255   0] [181 223 242]
[  0 255   0] [177 219 238]
[  0 255   0] [179 221 240]
[  0 

 [182 223 238]
[  0 255   0] [186 222 240]
[  0 255   0] [181 220 235]
[  0 255   0] [182 221 235]
[  0 255   0] [186 222 238]
[  0 255   0] [187 220 239]
[  0 255   0] [187 220 239]
[  0 255   0] [184 222 240]
[  0 255   0] [181 222 237]
[  0 255   0] [183 225 238]
[  0 255   0] [182 221 235]
[  0 255   0] [184 220 236]
[  0 255   0] [184 221 241]
[  0 255   0] [186 224 242]
[  0 255   0] [194 226 237]
[  0 255   0] [224 243 248]
[  0 255   0] [162 194 207]
[  0 255   0] [201 233 246]
[  0 255   0] [204 236 249]
[  0 255   0] [198 230 243]
[  0 255   0] [196 228 241]
[  0 255   0] [202 234 247]
[  0 255   0] [207 236 250]
[  0 255   0] [203 232 246]
[  0 255   0] [199 228 242]
[  0 255   0] [203 232 246]
[  0 255   0] [206 235 249]
[  0 255   0] [200 229 243]
[  0 255   0] [202 231 245]
[  0 255   0] [201 233 246]
[  0 255   0] [204 236 249]
[  0 255   0] [201 233 246]
[  0 255   0] [196 228 241]
[  0 255   0] [202 234 247]
[  0 255   0] [204 236 249]
[  0 255   0] [200 232 245]
[  0 

 [173 215 234]
[  0 255   0] [175 217 236]
[  0 255   0] [188 228 247]
[  0 255   0] [189 229 248]
[  0 255   0] [176 216 235]
[  0 255   0] [176 216 235]
[  0 255   0] [188 228 247]
[  0 255   0] [190 230 249]
[  0 255   0] [175 218 239]
[  0 255   0] [175 218 239]
[  0 255   0] [184 227 248]
[  0 255   0] [186 229 250]
[  0 255   0] [176 219 240]
[  0 255   0] [178 220 239]
[  0 255   0] [187 229 248]
[  0 255   0] [187 229 248]
[  0 255   0] [174 216 235]
[  0 255   0] [177 219 238]
[  0 255   0] [184 226 245]
[  0 255   0] [183 224 246]
[  0 255   0] [178 219 241]
[  0 255   0] [177 218 240]
[  0 255   0] [184 225 247]
[  0 255   0] [186 227 249]
[  0 255   0] [177 218 240]
[  0 255   0] [175 216 238]
[  0 255   0] [183 224 246]
[  0 255   0] [183 224 246]
[  0 255   0] [181 222 244]
[  0 255   0] [174 215 237]
[  0 255   0] [183 225 244]
[  0 255   0] [188 228 247]
[  0 255   0] [179 219 238]
[  0 255   0] [176 216 235]
[  0 255   0] [181 222 244]
[  0 255   0] [185 226 248]
[  0 

[178 218 236]
[  0 255   0] [178 218 236]
[  0 255   0] [186 226 244]
[  0 255   0] [186 226 244]
[  0 255   0] [180 220 238]
[  0 255   0] [179 219 237]
[  0 255   0] [186 226 244]
[  0 255   0] [185 225 243]
[  0 255   0] [179 219 237]
[  0 255   0] [178 218 236]
[  0 255   0] [186 226 244]
[  0 255   0] [186 226 244]
[  0 255   0] [180 220 238]
[  0 255   0] [179 219 237]
[  0 255   0] [183 227 244]
[  0 255   0] [182 226 243]
[  0 255   0] [176 220 237]
[  0 255   0] [175 219 236]
[  0 255   0] [183 227 244]
[  0 255   0] [182 226 243]
[  0 255   0] [176 220 237]
[  0 255   0] [175 219 236]
[  0 255   0] [182 226 243]
[  0 255   0] [182 226 243]
[  0 255   0] [176 220 237]
[  0 255   0] [174 218 235]
[  0 255   0] [183 227 244]
[  0 255   0] [185 228 245]
[  0 255   0] [179 222 239]
[  0 255   0] [176 219 236]
[  0 255   0] [183 226 243]
[  0 255   0] [184 227 244]
[  0 255   0] [178 221 238]
[  0 255   0] [175 218 235]
[  0 255   0] [183 226 243]
[  0 255   0] [185 228 245]
[  0 2

 [185 223 241]
[  0 255   0] [180 218 236]
[  0 255   0] [182 220 238]
[  0 255   0] [178 221 242]
[  0 255   0] [181 224 245]
[  0 255   0] [176 219 240]
[  0 255   0] [175 216 238]
[  0 255   0] [182 224 243]
[  0 255   0] [180 222 241]
[  0 255   0] [175 217 236]
[  0 255   0] [178 220 239]
[  0 255   0] [180 222 241]
[  0 255   0] [182 224 243]
[  0 255   0] [175 217 236]
[  0 255   0] [180 222 241]
[  0 255   0] [178 220 239]
[  0 255   0] [183 225 244]
[  0 255   0] [176 218 237]
[  0 255   0] [178 220 239]
[  0 255   0] [181 222 244]
[  0 255   0] [181 222 244]
[  0 255   0] [177 218 240]
[  0 255   0] [178 220 239]
[  0 255   0] [180 222 241]
[  0 255   0] [183 223 242]
[  0 255   0] [179 219 238]
[  0 255   0] [179 219 238]
[  0 255   0] [181 221 240]
[  0 255   0] [186 226 245]
[  0 255   0] [178 218 237]
[  0 255   0] [181 221 240]
[  0 255   0] [176 218 237]
[  0 255   0] [185 226 248]
[  0 255   0] [177 218 240]
[  0 255   0] [176 217 239]
[  0 255   0] [178 221 238]
[  0 

[  0 255   0] [180 224 241]
[  0 255   0] [178 222 239]
[  0 255   0] [178 222 239]
[  0 255   0] [180 223 240]
[  0 255   0] [181 224 241]
[  0 255   0] [179 222 239]
[  0 255   0] [176 219 236]
[  0 255   0] [178 221 238]
[  0 255   0] [181 224 241]
[  0 255   0] [178 221 238]
[  0 255   0] [180 223 240]
[  0 255   0] [181 224 241]
[  0 255   0] [181 224 241]
[  0 255   0] [179 222 239]
[  0 255   0] [178 221 238]
[  0 255   0] [180 223 240]
[  0 255   0] [183 226 243]
[  0 255   0] [178 221 238]
[  0 255   0] [179 222 239]
[  0 255   0] [181 224 241]
[  0 255   0] [180 223 240]
[  0 255   0] [178 221 238]
[  0 255   0] [177 220 237]
[  0 255   0] [178 221 238]
[  0 255   0] [181 224 241]
[  0 255   0] [180 220 239]
[  0 255   0] [181 221 240]
[  0 255   0] [182 222 241]
[  0 255   0] [181 221 240]
[  0 255   0] [180 220 239]
[  0 255   0] [180 220 239]
[  0 255   0] [181 221 240]
[  0 255   0] [183 223 242]
[  0 255   0] [182 222 241]
[  0 255   0] [180 220 239]
[  0 255   0] [181 2


[  0 255   0] [179 219 238]
[  0 255   0] [181 221 239]
[  0 255   0] [182 222 240]
[  0 255   0] [187 227 245]
[  0 255   0] [179 219 237]
[  0 255   0] [181 221 239]
[  0 255   0] [182 220 238]
[  0 255   0] [188 226 244]
[  0 255   0] [178 218 236]
[  0 255   0] [182 222 240]
[  0 255   0] [182 222 240]
[  0 255   0] [187 227 246]
[  0 255   0] [179 219 238]
[  0 255   0] [182 222 241]
[  0 255   0] [181 221 239]
[  0 255   0] [187 227 245]
[  0 255   0] [178 218 236]
[  0 255   0] [182 222 240]
[  0 255   0] [181 221 239]
[  0 255   0] [187 227 246]
[  0 255   0] [178 218 237]
[  0 255   0] [182 222 241]
[  0 255   0] [179 219 238]
[  0 255   0] [187 227 246]
[  0 255   0] [180 220 239]
[  0 255   0] [180 222 241]
[  0 255   0] [177 219 238]
[  0 255   0] [186 228 247]
[  0 255   0] [179 221 240]
[  0 255   0] [180 222 241]
[  0 255   0] [176 218 237]
[  0 255   0] [185 227 246]
[  0 255   0] [179 221 240]
[  0 255   0] [180 222 241]
[  0 255   0] [176 218 237]
[  0 255   0] [185 

 [179 221 240]
[  0 255   0] [183 225 244]
[  0 255   0] [180 222 241]
[  0 255   0] [178 220 239]
[  0 255   0] [181 223 242]
[  0 255   0] [183 225 244]
[  0 255   0] [182 222 241]
[  0 255   0] [179 219 238]
[  0 255   0] [180 220 239]
[  0 255   0] [184 224 243]
[  0 255   0] [183 223 242]
[  0 255   0] [179 219 238]
[  0 255   0] [180 220 239]
[  0 255   0] [186 226 245]
[  0 255   0] [182 222 241]
[  0 255   0] [180 220 239]
[  0 255   0] [181 221 240]
[  0 255   0] [185 225 244]
[  0 255   0] [183 223 242]
[  0 255   0] [179 219 238]
[  0 255   0] [181 221 240]
[  0 255   0] [186 226 245]
[  0 255   0] [181 221 240]
[  0 255   0] [179 219 238]
[  0 255   0] [180 220 239]
[  0 255   0] [183 223 242]
[  0 255   0] [181 221 240]
[  0 255   0] [177 217 236]
[  0 255   0] [179 219 238]
[  0 255   0] [184 224 243]
[  0 255   0] [183 223 242]
[  0 255   0] [180 220 239]
[  0 255   0] [181 221 240]
[  0 255   0] [185 225 244]
[  0 255   0] [183 223 242]
[  0 255   0] [179 219 238]
[  0 

 [185 224 239]
[  0 255   0] [184 223 238]
[  0 255   0] [180 219 234]
[  0 255   0] [176 219 236]
[  0 255   0] [180 223 240]
[  0 255   0] [179 222 239]
[  0 255   0] [176 219 236]
[  0 255   0] [176 219 236]
[  0 255   0] [181 224 241]
[  0 255   0] [181 224 241]
[  0 255   0] [176 219 236]
[  0 255   0] [176 219 236]
[  0 255   0] [180 223 240]
[  0 255   0] [180 223 240]
[  0 255   0] [176 219 236]
[  0 255   0] [176 219 236]
[  0 255   0] [181 224 241]
[  0 255   0] [180 223 240]
[  0 255   0] [176 219 236]
[  0 255   0] [181 218 238]
[  0 255   0] [184 221 241]
[  0 255   0] [184 221 241]
[  0 255   0] [180 217 237]
[  0 255   0] [181 218 238]
[  0 255   0] [185 222 242]
[  0 255   0] [185 222 242]
[  0 255   0] [181 218 238]
[  0 255   0] [180 217 237]
[  0 255   0] [184 221 241]
[  0 255   0] [184 221 241]
[  0 255   0] [181 218 238]
[  0 255   0] [180 217 237]
[  0 255   0] [184 221 241]
[  0 255   0] [184 221 241]
[  0 255   0] [180 217 237]
[  0 255   0] [180 217 237]
[  0 

[197 227 238]
[  0 255   0] [202 232 243]
[  0 255   0] [203 231 242]
[  0 255   0] [208 235 249]
[  0 255   0] [203 230 244]
[  0 255   0] [199 226 240]
[  0 255   0] [207 236 250]
[  0 255   0] [204 235 250]
[  0 255   0] [161 194 209]
[  0 255   0] [183 218 232]
[  0 255   0] [192 228 244]
[  0 255   0] [191 227 243]
[  0 255   0] [179 218 233]
[  0 255   0] [177 216 231]
[  0 255   0] [192 228 244]
[  0 255   0] [192 228 244]
[  0 255   0] [178 215 235]
[  0 255   0] [178 215 235]
[  0 255   0] [188 225 245]
[  0 255   0] [188 228 247]
[  0 255   0] [176 216 235]
[  0 255   0] [177 217 236]
[  0 255   0] [188 228 247]
[  0 255   0] [188 228 247]
[  0 255   0] [175 217 236]
[  0 255   0] [173 215 234]
[  0 255   0] [184 226 245]
[  0 255   0] [188 230 249]
[  0 255   0] [174 216 235]
[  0 255   0] [172 215 234]
[  0 255   0] [184 227 246]
[  0 255   0] [186 229 248]
[  0 255   0] [180 219 234]
[  0 255   0] [178 217 232]
[  0 255   0] [189 228 243]
[  0 255   0] [192 231 246]
[  0 2

[  0 255   0] [180 218 236]
[  0 255   0] [190 228 246]
[  0 255   0] [187 225 243]
[  0 255   0] [178 216 234]
[  0 255   0] [179 217 235]
[  0 255   0] [192 230 248]
[  0 255   0] [187 225 243]
[  0 255   0] [178 216 234]
[  0 255   0] [180 218 236]
[  0 255   0] [191 229 247]
[  0 255   0] [186 224 242]
[  0 255   0] [177 215 233]
[  0 255   0] [180 218 236]
[  0 255   0] [190 228 246]
[  0 255   0] [189 227 245]
[  0 255   0] [180 218 236]
[  0 255   0] [179 217 235]
[  0 255   0] [190 228 246]
[  0 255   0] [188 226 244]
[  0 255   0] [179 217 235]
[  0 255   0] [179 217 235]
[  0 255   0] [187 227 245]
[  0 255   0] [187 227 245]
[  0 255   0] [177 217 235]
[  0 255   0] [176 216 234]
[  0 255   0] [187 227 245]
[  0 255   0] [186 226 244]
[  0 255   0] [177 217 235]
[  0 255   0] [177 217 235]
[  0 255   0] [187 227 245]
[  0 255   0] [187 227 245]
[  0 255   0] [178 218 236]
[  0 255   0] [177 217 235]
[  0 255   0] [187 227 245]
[  0 255   0] [185 225 243]
[  0 255   0] [176 2

 [178 218 236]
[  0 255   0] [178 218 236]
[  0 255   0] [185 225 243]
[  0 255   0] [186 226 244]
[  0 255   0] [179 219 237]
[  0 255   0] [177 215 233]
[  0 255   0] [187 225 243]
[  0 255   0] [189 227 245]
[  0 255   0] [181 219 237]
[  0 255   0] [179 217 235]
[  0 255   0] [187 225 243]
[  0 255   0] [188 226 244]
[  0 255   0] [182 220 238]
[  0 255   0] [178 216 234]
[  0 255   0] [186 224 242]
[  0 255   0] [189 227 245]
[  0 255   0] [182 220 238]
[  0 255   0] [178 216 234]
[  0 255   0] [186 224 242]
[  0 255   0] [190 228 246]
[  0 255   0] [182 220 238]
[  0 255   0] [172 214 233]
[  0 255   0] [181 225 242]
[  0 255   0] [186 231 245]
[  0 255   0] [177 220 235]
[  0 255   0] [176 214 232]
[  0 255   0] [186 223 243]
[  0 255   0] [187 229 248]
[  0 255   0] [176 220 237]
[  0 255   0] [172 215 230]
[  0 255   0] [184 225 240]
[  0 255   0] [191 229 247]
[  0 255   0] [181 221 240]
[  0 255   0] [179 216 236]
[  0 255   0] [195 227 240]
[  0 255   0] [230 248 255]
[  0 

 [180 220 238]
[  0 255   0] [180 219 234]
[  0 255   0] [184 223 238]
[  0 255   0] [183 222 237]
[  0 255   0] [179 218 233]
[  0 255   0] [180 219 234]
[  0 255   0] [185 224 239]
[  0 255   0] [185 224 239]
[  0 255   0] [179 218 233]
[  0 255   0] [181 220 235]
[  0 255   0] [185 224 239]
[  0 255   0] [184 223 238]
[  0 255   0] [180 219 234]
[  0 255   0] [181 220 235]
[  0 255   0] [186 225 240]
[  0 255   0] [185 224 239]
[  0 255   0] [180 219 234]
[  0 255   0] [177 217 235]
[  0 255   0] [182 222 240]
[  0 255   0] [182 222 240]
[  0 255   0] [178 218 236]
[  0 255   0] [178 218 236]
[  0 255   0] [183 223 241]
[  0 255   0] [183 223 241]
[  0 255   0] [178 218 236]
[  0 255   0] [178 218 236]
[  0 255   0] [183 223 241]
[  0 255   0] [183 223 241]
[  0 255   0] [178 218 236]
[  0 255   0] [179 219 237]
[  0 255   0] [183 223 241]
[  0 255   0] [183 223 241]
[  0 255   0] [178 218 236]
[  0 255   0] [182 220 238]
[  0 255   0] [185 223 241]
[  0 255   0] [184 222 240]
[  0 


[  0 255   0] [181 221 240]
[  0 255   0] [186 224 242]
[  0 255   0] [196 228 241]
[  0 255   0] [225 244 249]
[  0 255   0] [162 194 207]
[  0 255   0] [200 232 245]
[  0 255   0] [199 231 244]
[  0 255   0] [201 230 244]
[  0 255   0] [207 236 250]
[  0 255   0] [204 233 247]
[  0 255   0] [200 229 243]
[  0 255   0] [200 229 243]
[  0 255   0] [206 235 249]
[  0 255   0] [202 231 245]
[  0 255   0] [201 230 244]
[  0 255   0] [202 231 245]
[  0 255   0] [204 233 247]
[  0 255   0] [203 232 246]
[  0 255   0] [201 230 244]
[  0 255   0] [200 229 243]
[  0 255   0] [204 233 247]
[  0 255   0] [202 231 245]
[  0 255   0] [201 230 244]
[  0 255   0] [202 231 245]
[  0 255   0] [203 232 246]
[  0 255   0] [202 231 245]
[  0 255   0] [200 229 243]
[  0 255   0] [199 228 242]
[  0 255   0] [206 235 249]
[  0 255   0] [203 232 246]
[  0 255   0] [199 228 242]
[  0 255   0] [202 231 245]
[  0 255   0] [206 235 249]
[  0 255   0] [202 231 245]
[  0 255   0] [198 227 241]
[  0 255   0] [202 


[  0 255   0] [179 220 235]
[  0 255   0] [186 227 242]
[  0 255   0] [186 227 242]
[  0 255   0] [180 221 236]
[  0 255   0] [179 220 235]
[  0 255   0] [185 226 241]
[  0 255   0] [185 226 241]
[  0 255   0] [179 220 235]
[  0 255   0] [179 220 235]
[  0 255   0] [185 226 241]
[  0 255   0] [185 226 241]
[  0 255   0] [178 219 234]
[  0 255   0] [181 221 239]
[  0 255   0] [184 224 242]
[  0 255   0] [184 224 242]
[  0 255   0] [180 220 238]
[  0 255   0] [180 220 238]
[  0 255   0] [184 224 242]
[  0 255   0] [184 224 242]
[  0 255   0] [180 220 238]
[  0 255   0] [181 221 239]
[  0 255   0] [183 223 241]
[  0 255   0] [182 222 240]
[  0 255   0] [179 219 237]
[  0 255   0] [181 221 239]
[  0 255   0] [185 225 243]
[  0 255   0] [184 224 242]
[  0 255   0] [178 218 236]
[  0 255   0] [180 220 238]
[  0 255   0] [183 223 241]
[  0 255   0] [182 222 240]
[  0 255   0] [179 219 237]
[  0 255   0] [180 220 238]
[  0 255   0] [185 225 243]
[  0 255   0] [185 225 243]
[  0 255   0] [180 

 [182 223 238]
[  0 255   0] [183 224 239]
[  0 255   0] [181 222 237]
[  0 255   0] [181 222 237]
[  0 255   0] [182 223 238]
[  0 255   0] [186 227 242]
[  0 255   0] [182 223 238]
[  0 255   0] [180 221 236]
[  0 255   0] [183 224 239]
[  0 255   0] [184 225 240]
[  0 255   0] [182 223 238]
[  0 255   0] [181 222 237]
[  0 255   0] [181 222 237]
[  0 255   0] [185 226 241]
[  0 255   0] [183 224 239]
[  0 255   0] [180 221 236]
[  0 255   0] [179 222 237]
[  0 255   0] [183 226 241]
[  0 255   0] [180 223 238]
[  0 255   0] [177 220 235]
[  0 255   0] [180 223 238]
[  0 255   0] [185 225 243]
[  0 255   0] [180 223 238]
[  0 255   0] [177 220 235]
[  0 255   0] [183 224 239]
[  0 255   0] [190 226 244]
[  0 255   0] [185 221 239]
[  0 255   0] [178 218 236]
[  0 255   0] [181 224 239]
[  0 255   0] [183 227 240]
[  0 255   0] [184 223 237]
[  0 255   0] [183 222 237]
[  0 255   0] [184 221 241]
[  0 255   0] [186 224 242]
[  0 255   0] [200 229 243]
[  0 255   0] [227 246 251]
[  0 

[179 222 239]
[  0 255   0] [178 221 238]
[  0 255   0] [179 222 239]
[  0 255   0] [182 225 242]
[  0 255   0] [177 220 237]
[  0 255   0] [177 220 237]
[  0 255   0] [179 222 239]
[  0 255   0] [182 225 242]
[  0 255   0] [177 220 237]
[  0 255   0] [176 219 234]
[  0 255   0] [179 222 237]
[  0 255   0] [182 225 240]
[  0 255   0] [176 219 234]
[  0 255   0] [178 221 236]
[  0 255   0] [178 221 236]
[  0 255   0] [181 224 239]
[  0 255   0] [178 221 236]
[  0 255   0] [176 219 234]
[  0 255   0] [180 223 238]
[  0 255   0] [182 225 240]
[  0 255   0] [176 219 234]
[  0 255   0] [178 221 236]
[  0 255   0] [179 222 237]
[  0 255   0] [181 224 239]
[  0 255   0] [178 221 236]
[  0 255   0] [178 219 234]
[  0 255   0] [183 224 239]
[  0 255   0] [184 225 240]
[  0 255   0] [180 221 236]
[  0 255   0] [179 220 235]
[  0 255   0] [181 222 237]
[  0 255   0] [182 223 238]
[  0 255   0] [181 222 237]
[  0 255   0] [179 220 235]
[  0 255   0] [182 223 238]
[  0 255   0] [182 223 238]
[  0 2

[199 231 244]
[  0 255   0] [199 228 242]
[  0 255   0] [204 233 247]
[  0 255   0] [208 237 251]
[  0 255   0] [202 231 245]
[  0 255   0] [198 227 241]
[  0 255   0] [205 234 248]
[  0 255   0] [207 236 250]
[  0 255   0] [201 230 244]
[  0 255   0] [200 229 243]
[  0 255   0] [205 234 248]
[  0 255   0] [207 236 250]
[  0 255   0] [202 231 245]
[  0 255   0] [195 224 238]
[  0 255   0] [205 234 248]
[  0 255   0] [209 238 252]
[  0 255   0] [202 231 245]
[  0 255   0] [198 227 241]
[  0 255   0] [202 231 245]
[  0 255   0] [205 234 248]
[  0 255   0] [204 233 247]
[  0 255   0] [197 226 240]
[  0 255   0] [204 233 247]
[  0 255   0] [208 237 251]
[  0 255   0] [205 234 248]
[  0 255   0] [198 227 241]
[  0 255   0] [200 229 243]
[  0 255   0] [205 234 248]
[  0 255   0] [206 235 249]
[  0 255   0] [199 228 242]
[  0 255   0] [201 230 244]
[  0 255   0] [207 236 250]
[  0 255   0] [206 235 249]
[  0 255   0] [199 228 242]
[  0 255   0] [202 231 245]
[  0 255   0] [208 237 251]
[  0 2


[  0 255   0] [179 222 239]
[  0 255   0] [178 221 238]
[  0 255   0] [181 224 241]
[  0 255   0] [186 229 244]
[  0 255   0] [178 221 236]
[  0 255   0] [175 218 233]
[  0 255   0] [179 222 237]
[  0 255   0] [189 232 247]
[  0 255   0] [180 223 238]
[  0 255   0] [177 220 235]
[  0 255   0] [182 225 240]
[  0 255   0] [187 230 245]
[  0 255   0] [179 222 237]
[  0 255   0] [175 218 233]
[  0 255   0] [180 223 238]
[  0 255   0] [188 231 246]
[  0 255   0] [180 223 238]
[  0 255   0] [177 220 235]
[  0 255   0] [182 225 240]
[  0 255   0] [188 229 244]
[  0 255   0] [181 222 237]
[  0 255   0] [176 217 232]
[  0 255   0] [182 223 238]
[  0 255   0] [189 230 245]
[  0 255   0] [183 224 239]
[  0 255   0] [178 219 234]
[  0 255   0] [183 224 239]
[  0 255   0] [189 230 245]
[  0 255   0] [182 223 238]
[  0 255   0] [176 217 232]
[  0 255   0] [182 223 238]
[  0 255   0] [189 230 245]
[  0 255   0] [184 225 240]
[  0 255   0] [178 219 234]
[  0 255   0] [182 223 238]
[  0 255   0] [188 

[188 228 246]
[  0 255   0] [180 223 238]
[  0 255   0] [174 218 231]
[  0 255   0] [188 227 241]
[  0 255   0] [192 230 248]
[  0 255   0] [182 222 241]
[  0 255   0] [180 218 236]
[  0 255   0] [196 228 241]
[  0 255   0] [231 250 255]
[  0 255   0] [165 197 210]
[  0 255   0] [196 228 241]
[  0 255   0] [198 230 243]
[  0 255   0] [201 233 246]
[  0 255   0] [200 232 245]
[  0 255   0] [200 229 243]
[  0 255   0] [202 231 245]
[  0 255   0] [201 230 244]
[  0 255   0] [202 231 245]
[  0 255   0] [199 228 242]
[  0 255   0] [200 229 243]
[  0 255   0] [203 232 246]
[  0 255   0] [202 231 245]
[  0 255   0] [200 229 243]
[  0 255   0] [200 229 243]
[  0 255   0] [202 231 245]
[  0 255   0] [205 234 248]
[  0 255   0] [200 229 243]
[  0 255   0] [198 227 241]
[  0 255   0] [202 231 245]
[  0 255   0] [204 233 247]
[  0 255   0] [203 232 246]
[  0 255   0] [201 230 244]
[  0 255   0] [202 231 245]
[  0 255   0] [203 232 246]
[  0 255   0] [199 228 242]
[  0 255   0] [200 229 243]
[  0 2


[  0 255   0] [179 222 239]
[  0 255   0] [177 220 237]
[  0 255   0] [181 224 241]
[  0 255   0] [180 223 240]
[  0 255   0] [179 222 239]
[  0 255   0] [179 222 239]
[  0 255   0] [177 220 237]
[  0 255   0] [177 220 237]
[  0 255   0] [181 224 241]
[  0 255   0] [178 221 238]
[  0 255   0] [179 222 239]
[  0 255   0] [178 221 238]
[  0 255   0] [179 222 239]
[  0 255   0] [180 223 240]
[  0 255   0] [178 221 238]
[  0 255   0] [178 221 238]
[  0 255   0] [181 224 241]
[  0 255   0] [182 222 240]
[  0 255   0] [180 220 238]
[  0 255   0] [181 221 239]
[  0 255   0] [183 223 241]
[  0 255   0] [181 221 239]
[  0 255   0] [179 219 237]
[  0 255   0] [180 220 238]
[  0 255   0] [184 224 242]
[  0 255   0] [182 222 240]
[  0 255   0] [181 221 239]
[  0 255   0] [182 222 240]
[  0 255   0] [183 223 241]
[  0 255   0] [181 221 239]
[  0 255   0] [179 219 237]
[  0 255   0] [181 221 239]
[  0 255   0] [183 223 241]
[  0 255   0] [182 222 240]
[  0 255   0] [179 219 237]
[  0 255   0] [181 


[  0 255   0] [181 221 239]
[  0 255   0] [184 224 242]
[  0 255   0] [183 223 241]
[  0 255   0] [181 221 239]
[  0 255   0] [179 219 237]
[  0 255   0] [185 225 243]
[  0 255   0] [184 224 242]
[  0 255   0] [178 218 236]
[  0 255   0] [179 219 237]
[  0 255   0] [187 227 245]
[  0 255   0] [186 226 244]
[  0 255   0] [177 217 235]
[  0 255   0] [182 222 240]
[  0 255   0] [184 224 242]
[  0 255   0] [183 223 241]
[  0 255   0] [180 220 238]
[  0 255   0] [182 222 240]
[  0 255   0] [186 226 244]
[  0 255   0] [185 225 243]
[  0 255   0] [180 220 238]
[  0 255   0] [181 221 239]
[  0 255   0] [183 223 241]
[  0 255   0] [182 222 240]
[  0 255   0] [179 219 237]
[  0 255   0] [181 221 239]
[  0 255   0] [185 225 243]
[  0 255   0] [184 224 242]
[  0 255   0] [179 219 237]
[  0 255   0] [181 221 239]
[  0 255   0] [184 224 242]
[  0 255   0] [184 224 242]
[  0 255   0] [181 221 239]
[  0 255   0] [181 221 239]
[  0 255   0] [184 224 242]
[  0 255   0] [184 224 242]
[  0 255   0] [181 

 [185 225 243]
[  0 255   0] [180 220 238]
[  0 255   0] [181 221 239]
[  0 255   0] [185 225 243]
[  0 255   0] [184 224 242]
[  0 255   0] [180 220 238]
[  0 255   0] [179 219 237]
[  0 255   0] [183 223 241]
[  0 255   0] [184 224 242]
[  0 255   0] [178 218 236]
[  0 255   0] [179 219 237]
[  0 255   0] [184 224 242]
[  0 255   0] [183 223 241]
[  0 255   0] [181 219 237]
[  0 255   0] [181 219 237]
[  0 255   0] [184 222 240]
[  0 255   0] [185 223 241]
[  0 255   0] [182 220 238]
[  0 255   0] [182 220 238]
[  0 255   0] [185 223 241]
[  0 255   0] [186 224 242]
[  0 255   0] [180 220 238]
[  0 255   0] [179 219 237]
[  0 255   0] [182 222 240]
[  0 255   0] [183 223 241]
[  0 255   0] [180 220 238]
[  0 255   0] [180 220 238]
[  0 255   0] [184 224 242]
[  0 255   0] [184 224 242]
[  0 255   0] [180 220 238]
[  0 255   0] [180 220 238]
[  0 255   0] [182 222 240]
[  0 255   0] [184 224 242]
[  0 255   0] [182 222 240]
[  0 255   0] [179 219 237]
[  0 255   0] [181 221 239]
[  0 

[216 248 255]
[  0 255   0] [212 246 255]
[  0 255   0] [208 242 255]
[  0 255   0] [205 240 254]
[  0 255   0] [192 229 243]
[  0 255   0] [182 218 234]
[  0 255   0] [182 221 236]
[  0 255   0] [185 224 239]
[  0 255   0] [185 224 239]
[  0 255   0] [179 217 235]
[  0 255   0] [181 219 237]
[  0 255   0] [183 222 237]
[  0 255   0] [185 224 239]
[  0 255   0] [182 218 234]
[  0 255   0] [181 217 233]
[  0 255   0] [179 212 227]
[  0 255   0] [158 191 206]
[  0 255   0] [162 195 210]
[  0 255   0] [183 217 230]
[  0 255   0] [179 213 226]
[  0 255   0] [187 219 232]
[  0 255   0] [181 213 226]
[  0 255   0] [186 218 231]
[  0 255   0] [185 217 230]
[  0 255   0] [189 218 232]
[  0 255   0] [185 214 228]
[  0 255   0] [187 216 230]
[  0 255   0] [184 213 227]
[  0 255   0] [189 218 233]
[  0 255   0] [182 213 228]
[  0 255   0] [184 215 230]
[  0 255   0] [180 213 229]
[  0 255   0] [183 216 232]
[  0 255   0] [181 214 230]
[  0 255   0] [183 216 232]
[  0 255   0] [179 212 228]
[  0 2

 [208 236 247]
[  0 255   0] [205 233 244]
[  0 255   0] [199 227 238]
[  0 255   0] [207 235 246]
[  0 255   0] [208 236 247]
[  0 255   0] [217 245 255]
[  0 255   0] [220 248 255]
[  0 255   0] [215 243 254]
[  0 255   0] [219 247 255]
[  0 255   0] [213 241 252]
[  0 255   0] [202 230 241]
[  0 255   0] [201 229 240]
[  0 255   0] [207 235 246]
[  0 255   0] [208 236 247]
[  0 255   0] [200 228 239]
[  0 255   0] [200 228 239]
[  0 255   0] [207 235 246]
[  0 255   0] [209 237 248]
[  0 255   0] [202 229 239]
[  0 255   0] [202 229 239]
[  0 255   0] [202 229 239]
[  0 255   0] [196 223 233]
[  0 255   0] [185 211 223]
[  0 255   0] [170 196 208]
[  0 255   0] [158 186 197]
[  0 255   0] [151 178 192]
[  0 255   0] [147 174 188]
[  0 255   0] [146 175 189]
[  0 255   0] [143 175 188]
[  0 255   0] [141 173 186]
[  0 255   0] [139 173 186]
[  0 255   0] [137 172 182]
[  0 255   0] [138 173 183]
[  0 255   0] [142 177 187]
[  0 255   0] [155 169 181]
[  0 255   0] [154 172 183]
[  0 

[  0 255   0] [177 219 232]
[  0 255   0] [187 229 242]
[  0 255   0] [186 228 241]
[  0 255   0] [177 219 232]
[  0 255   0] [177 219 232]
[  0 255   0] [186 228 241]
[  0 255   0] [186 228 241]
[  0 255   0] [177 219 232]
[  0 255   0] [176 218 231]
[  0 255   0] [188 230 243]
[  0 255   0] [186 228 241]
[  0 255   0] [177 219 232]
[  0 255   0] [176 218 231]
[  0 255   0] [187 229 242]
[  0 255   0] [187 229 242]
[  0 255   0] [178 220 233]
[  0 255   0] [176 218 231]
[  0 255   0] [186 228 241]
[  0 255   0] [184 226 239]
[  0 255   0] [178 220 233]
[  0 255   0] [178 220 233]
[  0 255   0] [185 227 240]
[  0 255   0] [185 227 240]
[  0 255   0] [179 221 234]
[  0 255   0] [176 218 231]
[  0 255   0] [186 228 241]
[  0 255   0] [185 227 240]
[  0 255   0] [179 221 234]
[  0 255   0] [177 219 232]
[  0 255   0] [184 226 239]
[  0 255   0] [186 228 241]
[  0 255   0] [179 221 234]
[  0 255   0] [175 217 230]
[  0 255   0] [184 226 239]
[  0 255   0] [186 228 241]
[  0 255   0] [181 2

 [183 221 239]
[  0 255   0] [186 224 242]
[  0 255   0] [183 221 239]
[  0 255   0] [181 219 237]
[  0 255   0] [183 221 239]
[  0 255   0] [186 224 242]
[  0 255   0] [184 222 240]
[  0 255   0] [179 217 235]
[  0 255   0] [181 219 237]
[  0 255   0] [185 223 241]
[  0 255   0] [184 222 240]
[  0 255   0] [180 218 236]
[  0 255   0] [181 219 237]
[  0 255   0] [184 222 240]
[  0 255   0] [184 222 240]
[  0 255   0] [180 218 236]
[  0 255   0] [180 218 236]
[  0 255   0] [184 222 240]
[  0 255   0] [184 222 240]
[  0 255   0] [181 219 237]
[  0 255   0] [182 220 238]
[  0 255   0] [186 224 242]
[  0 255   0] [185 223 241]
[  0 255   0] [181 219 237]
[  0 255   0] [181 219 237]
[  0 255   0] [185 223 241]
[  0 255   0] [185 223 241]
[  0 255   0] [180 218 236]
[  0 255   0] [181 219 237]
[  0 255   0] [184 222 240]
[  0 255   0] [184 222 240]
[  0 255   0] [179 217 235]
[  0 255   0] [179 217 235]
[  0 255   0] [183 221 239]
[  0 255   0] [184 222 240]
[  0 255   0] [182 220 238]
[  0 

[178 213 227]
[  0 255   0] [184 219 233]
[  0 255   0] [185 218 233]
[  0 255   0] [185 218 233]
[  0 255   0] [184 217 232]
[  0 255   0] [184 217 232]
[  0 255   0] [184 219 233]
[  0 255   0] [184 219 233]
[  0 255   0] [183 218 232]
[  0 255   0] [181 216 230]
[  0 255   0] [182 217 231]
[  0 255   0] [182 217 231]
[  0 255   0] [181 216 230]
[  0 255   0] [178 215 229]
[  0 255   0] [179 216 230]
[  0 255   0] [181 218 232]
[  0 255   0] [181 218 232]
[  0 255   0] [177 214 228]
[  0 255   0] [181 214 233]
[  0 255   0] [182 215 234]
[  0 255   0] [180 213 232]
[  0 255   0] [179 212 231]
[  0 255   0] [180 213 232]
[  0 255   0] [183 216 235]
[  0 255   0] [181 214 233]
[  0 255   0] [178 211 230]
[  0 255   0] [177 213 231]
[  0 255   0] [178 213 233]
[  0 255   0] [178 213 233]
[  0 255   0] [178 213 233]
[  0 255   0] [179 214 234]
[  0 255   0] [178 213 233]
[  0 255   0] [177 212 232]
[  0 255   0] [176 211 231]
[  0 255   0] [175 210 230]
[  0 255   0] [178 213 233]
[  0 2

 [179 223 240]
[  0 255   0] [183 226 241]
[  0 255   0] [180 221 236]
[  0 255   0] [181 219 237]
[  0 255   0] [182 222 241]
[  0 255   0] [183 223 242]
[  0 255   0] [195 227 240]
[  0 255   0] [224 243 250]
[  0 255   0] [161 195 208]
[  0 255   0] [198 230 243]
[  0 255   0] [198 230 243]
[  0 255   0] [201 230 244]
[  0 255   0] [203 232 246]
[  0 255   0] [202 229 243]
[  0 255   0] [202 229 243]
[  0 255   0] [202 231 245]
[  0 255   0] [203 232 246]
[  0 255   0] [198 230 243]
[  0 255   0] [199 231 244]
[  0 255   0] [201 233 246]
[  0 255   0] [202 231 245]
[  0 255   0] [200 229 243]
[  0 255   0] [201 230 244]
[  0 255   0] [204 231 245]
[  0 255   0] [206 235 249]
[  0 255   0] [202 231 245]
[  0 255   0] [199 228 242]
[  0 255   0] [202 231 245]
[  0 255   0] [204 233 247]
[  0 255   0] [200 229 243]
[  0 255   0] [199 228 242]
[  0 255   0] [204 233 247]
[  0 255   0] [202 231 245]
[  0 255   0] [203 232 246]
[  0 255   0] [203 230 244]
[  0 255   0] [204 231 245]
[  0 

[  0 255   0] [174 216 235]
[  0 255   0] [176 218 237]
[  0 255   0] [182 224 243]
[  0 255   0] [179 221 240]
[  0 255   0] [176 218 237]
[  0 255   0] [177 219 238]
[  0 255   0] [181 223 242]
[  0 255   0] [179 221 240]
[  0 255   0] [175 217 236]
[  0 255   0] [177 219 238]
[  0 255   0] [182 224 243]
[  0 255   0] [179 221 240]
[  0 255   0] [176 218 237]
[  0 255   0] [178 220 239]
[  0 255   0] [181 223 242]
[  0 255   0] [179 221 240]
[  0 255   0] [174 216 235]
[  0 255   0] [176 218 237]
[  0 255   0] [181 223 242]
[  0 255   0] [181 223 242]
[  0 255   0] [176 218 237]
[  0 255   0] [176 218 237]
[  0 255   0] [181 223 242]
[  0 255   0] [180 222 241]
[  0 255   0] [177 219 238]
[  0 255   0] [177 219 238]
[  0 255   0] [180 222 241]
[  0 255   0] [180 222 241]
[  0 255   0] [176 218 237]
[  0 255   0] [177 219 238]
[  0 255   0] [181 223 242]
[  0 255   0] [180 222 241]
[  0 255   0] [177 219 238]
[  0 255   0] [178 220 239]
[  0 255   0] [180 222 241]
[  0 255   0] [181 2

[  0 255   0] [193 228 242]
[  0 255   0] [186 221 235]
[  0 255   0] [184 219 233]
[  0 255   0] [192 227 241]
[  0 255   0] [191 226 240]
[  0 255   0] [186 221 235]
[  0 255   0] [186 221 235]
[  0 255   0] [192 227 241]
[  0 255   0] [192 227 241]
[  0 255   0] [188 223 237]
[  0 255   0] [185 220 234]
[  0 255   0] [193 228 242]
[  0 255   0] [192 227 241]
[  0 255   0] [187 222 236]
[  0 255   0] [186 221 235]
[  0 255   0] [191 226 240]
[  0 255   0] [192 227 241]
[  0 255   0] [187 222 236]
[  0 255   0] [183 218 232]
[  0 255   0] [190 225 239]
[  0 255   0] [192 227 241]
[  0 255   0] [188 223 237]
[  0 255   0] [185 220 234]
[  0 255   0] [190 225 239]
[  0 255   0] [194 229 243]
[  0 255   0] [190 225 239]
[  0 255   0] [184 219 233]
[  0 255   0] [190 225 239]
[  0 255   0] [192 227 241]
[  0 255   0] [188 223 237]
[  0 255   0] [184 219 233]
[  0 255   0] [190 225 239]
[  0 255   0] [194 229 243]
[  0 255   0] [189 224 238]
[  0 255   0] [184 219 233]
[  0 255   0] [189 2

 [228 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 255   0] [228 247 254]
[  0 255   0] [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [225 244 251]
[  0 255   0] [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [224 243 250]
[  0 255   0] [227 246 253]
[  0 255   0] [229 248 255]
[  0 255   0] [224 243 250]
[  0 255   0] [228 247 254]
[  0 255   0] [225 244 251]
[  0 255   0] [227 246 253]
[  0 255   0] [228 247 254]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 255   0] [228 247 254]
[  0 255   0] [226 245 252]
[  0 255   0] [225 244 251]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 255   0] [228 247 254]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 255   0] [228 247 254]
[  0 255   0] [228 247 254]
[  0 255   0] [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 

 [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [228 247 254]
[  0 255   0] [228 247 254]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [227 246 253]
[  0 255   0] [225 244 251]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 255   0] [227 246 253]
[  0 255   0] [228 247 254]
[  0 255   0] [226 245 252]
[  0 255   0] [226 245 252]
[  0 

 [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [250 254 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [250 254 255]
[  0 255   0] [251 255 255]
[  0 255   0] [250 254 255]
[  0 255   0] [249 253 254]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [250 254 255]
[  0 255   0] [250 254 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [250 254 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [249 253 254]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [249 253 254]
[  0 255   0] [250 254 255]
[  0 255   0] [251 255 255]
[  0 255   0] [250 254 255]
[  0 255   0] [250 254 255]
[  0 255   0] [249 253 254]
[  0 255   0] [251 255 255]
[  0 255   0] [251 255 255]
[  0 255   0] [250 254 255]
[  0 255   0] [249 253 254]
[  0 


[  0 255   0] [255 254 253]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 254 253]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 254 253]
[  0 255   0] [255 254 253]
[  0 255   0] [255 253 252]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 253 252]
[  0 255   0] [255 254 253]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 254 253]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 254 253]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 253 252]
[  0 255   0] [255 254 253]
[  0 255   0] [255 255 254]
[  0 255   0] [255 254 253]
[  0 255   0] [255 255 254]
[  0 255   0] [255 

 [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 255   0] [255 255 254]
[  0 

 [179 215 233]
[  0 255   0] [187 222 242]
[  0 255   0] [189 229 248]
[  0 255   0] [179 223 240]
[  0 255   0] [172 215 230]
[  0 255   0] [185 226 241]
[  0 255   0] [191 229 247]
[  0 255   0] [180 220 239]
[  0 255   0] [177 217 236]
[  0 255   0] [196 228 241]
[  0 255   0] [230 249 255]
[  0 255   0] [159 193 206]
[  0 255   0] [199 231 244]
[  0 255   0] [201 233 246]
[  0 255   0] [201 230 244]
[  0 255   0] [201 230 244]
[  0 255   0] [203 230 244]
[  0 255   0] [204 231 245]
[  0 255   0] [199 228 242]
[  0 255   0] [202 231 245]
[  0 255   0] [199 231 244]
[  0 255   0] [199 231 244]
[  0 255   0] [200 232 245]
[  0 255   0] [201 230 244]
[  0 255   0] [202 231 245]
[  0 255   0] [201 230 244]
[  0 255   0] [201 228 242]
[  0 255   0] [202 232 243]
[  0 255   0] [200 230 241]
[  0 255   0] [200 230 241]
[  0 255   0] [202 232 243]
[  0 255   0] [209 239 250]
[  0 255   0] [218 246 255]
[  0 255   0] [217 245 255]
[  0 255   0] [210 238 249]
[  0 255   0] [203 231 242]
[  0 


[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 


[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 255 255]
[  0 255   0] [253 


[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 

 [189 225 241]
[  0 255   0] [177 216 231]
[  0 255   0] [182 220 238]
[  0 255   0] [186 226 244]
[  0 255   0] [191 231 249]
[  0 255   0] [175 215 233]
[  0 255   0] [178 218 236]
[  0 255   0] [188 228 246]
[  0 255   0] [188 228 246]
[  0 255   0] [177 217 235]
[  0 255   0] [177 217 235]
[  0 255   0] [186 227 242]
[  0 255   0] [189 230 245]
[  0 255   0] [178 214 238]
[  0 255   0] [175 216 238]
[  0 255   0] [184 227 246]
[  0 255   0] [184 227 242]
[  0 255   0] [188 220 233]
[  0 255   0] [231 247 255]
[  0 255   0] [251 252 255]
[  0 255   0] [255 250 255]
[  0 255   0] [255 252 255]
[  0 255   0] [255 253 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 255 255]
[  0 255   0] [255 254 255]
[  0 255   0] [255 253 255]
[  0 255   0] [255 253 255]
[  0 255   0] [255 252 255]
[  0 255   0] [255 254 255]
[  0 255   0] [255 254 255]
[  0 255   0] [255 254 255]
[  0 255   0] [255 254 255]
[  0 255   0] [255 254 255]
[  0 255   0] [255 254 255]
[  0 255   0] [255 254 255]
[  0 

 [177 220 235]
[  0 255   0] [180 220 238]
[  0 255   0] [189 225 243]
[  0 255   0] [194 227 246]
[  0 255   0] [186 219 238]
[  0 255   0] [177 217 236]
[  0 255   0] [182 225 242]
[  0 255   0] [185 228 243]
[  0 255   0] [180 221 236]
[  0 255   0] [181 217 235]
[  0 255   0] [188 223 243]
[  0 255   0] [187 227 246]
[  0 255   0] [178 222 239]
[  0 255   0] [175 218 233]
[  0 255   0] [184 225 240]
[  0 255   0] [189 227 245]
[  0 255   0] [181 221 240]
[  0 255   0] [178 218 237]
[  0 255   0] [195 227 240]
[  0 255   0] [228 247 254]
[  0 255   0] [159 193 206]
[  0 255   0] [200 232 245]
[  0 255   0] [202 234 247]
[  0 255   0] [202 231 245]
[  0 255   0] [200 229 243]
[  0 255   0] [203 230 244]
[  0 255   0] [205 232 246]
[  0 255   0] [201 230 244]
[  0 255   0] [201 230 244]
[  0 255   0] [201 233 246]
[  0 255   0] [202 234 247]
[  0 255   0] [200 232 245]
[  0 255   0] [200 229 243]
[  0 255   0] [203 232 246]
[  0 255   0] [204 233 247]
[  0 255   0] [202 229 243]
[  0 

In [3]:
a = [1, 2, 3, 4, 5, 6]
print(a[0:3])

[1, 2, 3]
